// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Symbiosis.Pulumi.Symbiosis.Outputs
{

    [OutputType]
    public sealed class NodePoolAutoscaling
    {
        public readonly bool Enabled;
        public readonly int MaxSize;
        public readonly int MinSize;

        [OutputConstructor]
        private NodePoolAutoscaling(
            bool enabled,

            int maxSize,

            int minSize)
        {
            Enabled = enabled;
            MaxSize = maxSize;
            MinSize = minSize;
        }
    }
}
