// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Symbiosis.Pulumi.Symbiosis.Inputs
{

    public sealed class NodePoolAutoscalingGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("maxSize", required: true)]
        public Input<int> MaxSize { get; set; } = null!;

        [Input("minSize", required: true)]
        public Input<int> MinSize { get; set; } = null!;

        public NodePoolAutoscalingGetArgs()
        {
        }
        public static new NodePoolAutoscalingGetArgs Empty => new NodePoolAutoscalingGetArgs();
    }
}
