// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// The ApiKey used to authenticate requests towards Symbiosis.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "symbiosis:apiKey")
}

// Endpoint for reaching the symbiosis API. Used for debugging or when accessed through a proxy.
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "symbiosis:endpoint")
}
