# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .cluster import *
from .cluster_service_account import *
from .node_pool import *
from .provider import *
from .team_member import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import symbiosis_pulumi.config as __config
    config = __config
else:
    config = _utilities.lazy_import('symbiosis_pulumi.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "symbiosis",
  "mod": "index/cluster",
  "fqn": "symbiosis_pulumi",
  "classes": {
   "symbiosis:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "symbiosis",
  "mod": "index/clusterServiceAccount",
  "fqn": "symbiosis_pulumi",
  "classes": {
   "symbiosis:index/clusterServiceAccount:ClusterServiceAccount": "ClusterServiceAccount"
  }
 },
 {
  "pkg": "symbiosis",
  "mod": "index/nodePool",
  "fqn": "symbiosis_pulumi",
  "classes": {
   "symbiosis:index/nodePool:NodePool": "NodePool"
  }
 },
 {
  "pkg": "symbiosis",
  "mod": "index/teamMember",
  "fqn": "symbiosis_pulumi",
  "classes": {
   "symbiosis:index/teamMember:TeamMember": "TeamMember"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "symbiosis",
  "token": "pulumi:providers:symbiosis",
  "fqn": "symbiosis_pulumi",
  "class": "Provider"
 }
]
"""
)
