// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package symbiosis

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NodePoolTaint struct {
	// Taint effect. Can be either NoSchedule, PreferNoSchedule or NoExecute. See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Effect string `pulumi:"effect"`
	Key    string `pulumi:"key"`
	Value  string `pulumi:"value"`
}

// NodePoolTaintInput is an input type that accepts NodePoolTaintArgs and NodePoolTaintOutput values.
// You can construct a concrete instance of `NodePoolTaintInput` via:
//
//          NodePoolTaintArgs{...}
type NodePoolTaintInput interface {
	pulumi.Input

	ToNodePoolTaintOutput() NodePoolTaintOutput
	ToNodePoolTaintOutputWithContext(context.Context) NodePoolTaintOutput
}

type NodePoolTaintArgs struct {
	// Taint effect. Can be either NoSchedule, PreferNoSchedule or NoExecute. See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Effect pulumi.StringInput `pulumi:"effect"`
	Key    pulumi.StringInput `pulumi:"key"`
	Value  pulumi.StringInput `pulumi:"value"`
}

func (NodePoolTaintArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NodePoolTaint)(nil)).Elem()
}

func (i NodePoolTaintArgs) ToNodePoolTaintOutput() NodePoolTaintOutput {
	return i.ToNodePoolTaintOutputWithContext(context.Background())
}

func (i NodePoolTaintArgs) ToNodePoolTaintOutputWithContext(ctx context.Context) NodePoolTaintOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePoolTaintOutput)
}

// NodePoolTaintArrayInput is an input type that accepts NodePoolTaintArray and NodePoolTaintArrayOutput values.
// You can construct a concrete instance of `NodePoolTaintArrayInput` via:
//
//          NodePoolTaintArray{ NodePoolTaintArgs{...} }
type NodePoolTaintArrayInput interface {
	pulumi.Input

	ToNodePoolTaintArrayOutput() NodePoolTaintArrayOutput
	ToNodePoolTaintArrayOutputWithContext(context.Context) NodePoolTaintArrayOutput
}

type NodePoolTaintArray []NodePoolTaintInput

func (NodePoolTaintArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodePoolTaint)(nil)).Elem()
}

func (i NodePoolTaintArray) ToNodePoolTaintArrayOutput() NodePoolTaintArrayOutput {
	return i.ToNodePoolTaintArrayOutputWithContext(context.Background())
}

func (i NodePoolTaintArray) ToNodePoolTaintArrayOutputWithContext(ctx context.Context) NodePoolTaintArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NodePoolTaintArrayOutput)
}

type NodePoolTaintOutput struct{ *pulumi.OutputState }

func (NodePoolTaintOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NodePoolTaint)(nil)).Elem()
}

func (o NodePoolTaintOutput) ToNodePoolTaintOutput() NodePoolTaintOutput {
	return o
}

func (o NodePoolTaintOutput) ToNodePoolTaintOutputWithContext(ctx context.Context) NodePoolTaintOutput {
	return o
}

// Taint effect. Can be either NoSchedule, PreferNoSchedule or NoExecute. See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
func (o NodePoolTaintOutput) Effect() pulumi.StringOutput {
	return o.ApplyT(func(v NodePoolTaint) string { return v.Effect }).(pulumi.StringOutput)
}

func (o NodePoolTaintOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v NodePoolTaint) string { return v.Key }).(pulumi.StringOutput)
}

func (o NodePoolTaintOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v NodePoolTaint) string { return v.Value }).(pulumi.StringOutput)
}

type NodePoolTaintArrayOutput struct{ *pulumi.OutputState }

func (NodePoolTaintArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NodePoolTaint)(nil)).Elem()
}

func (o NodePoolTaintArrayOutput) ToNodePoolTaintArrayOutput() NodePoolTaintArrayOutput {
	return o
}

func (o NodePoolTaintArrayOutput) ToNodePoolTaintArrayOutputWithContext(ctx context.Context) NodePoolTaintArrayOutput {
	return o
}

func (o NodePoolTaintArrayOutput) Index(i pulumi.IntInput) NodePoolTaintOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NodePoolTaint {
		return vs[0].([]NodePoolTaint)[vs[1].(int)]
	}).(NodePoolTaintOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NodePoolTaintInput)(nil)).Elem(), NodePoolTaintArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NodePoolTaintArrayInput)(nil)).Elem(), NodePoolTaintArray{})
	pulumi.RegisterOutputType(NodePoolTaintOutput{})
	pulumi.RegisterOutputType(NodePoolTaintArrayOutput{})
}
