// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./cluster";
export * from "./clusterServiceAccount";
export * from "./nodePool";
export * from "./provider";
export * from "./teamMember";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { Cluster } from "./cluster";
import { ClusterServiceAccount } from "./clusterServiceAccount";
import { NodePool } from "./nodePool";
import { TeamMember } from "./teamMember";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "symbiosis:index/cluster:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "symbiosis:index/clusterServiceAccount:ClusterServiceAccount":
                return new ClusterServiceAccount(name, <any>undefined, { urn })
            case "symbiosis:index/nodePool:NodePool":
                return new NodePool(name, <any>undefined, { urn })
            case "symbiosis:index/teamMember:TeamMember":
                return new TeamMember(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("symbiosis", "index/cluster", _module)
pulumi.runtime.registerResourceModule("symbiosis", "index/clusterServiceAccount", _module)
pulumi.runtime.registerResourceModule("symbiosis", "index/nodePool", _module)
pulumi.runtime.registerResourceModule("symbiosis", "index/teamMember", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("symbiosis", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:symbiosis") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
